openapi: 3.0.3
info:
  title: API Recording Streamer
  description: API Recording Streamer
  version: 1.0.0
servers:
  - url: 'http://localhost:3002'
paths:
  /send-message:
    post:
      summary: Send a message ADS-B to the server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The message ADS-B
                  example: 'MSG,5,1,4837,A4A445,18147,2016/12/09,09:13:34.120,2016/12/09,09:13:35.077,,7250,,,,,,,0,,0,0'
      responses:
        200:
          description: The message was successfully sent to the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
